fix npm publish .DS_Store
vuejs/vue pull request #11740
Opened 2020-10-25 21:41 UTC by theskillwithin

**What kind of change does this PR introduce?** (check at least one)
- [x ] Bugfix
**Does this PR introduce a breaking change?** (check one)
- [ ] Yes
- [x ] No

prevent .DS_Store from being publish

see: https://unpkg.com/browse/vue@2.6.12/src/

2020-10-25 21:43 UTC, theskillwithin commented
https://github.com/vuejs/vue/issues/10112

2021-01-07 15:00 UTC, posva requested changes
Review based on testing with https://unpkg.com/browse/@posva/test-ds-store@1.0.3/

2021-01-07 15:00 UTC, posva commented on package.json
>      "src",
In order for the ignore rule to work, this one has to be more precise (like the other rules with extensions)

2021-01-07 15:54 UTC, theskillwithin commented
@posva I think someone should make a new PR, I deleted this forked repo so seems I can't edit this PR anymore

2021-01-07 15:55 UTC, posva commented
Thanks for the initiative though!

2021-01-07 15:55 UTC, closed without merging